# render.yaml
services:
    - type: worker
      name: telegram-session-bot
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: python -m app.bot
      envVars:
          - key: BOT_TOKEN
            sync: false
          - key: API_ID
            sync: false
          - key: API_HASH
            sync: false
